### ISSUE TITLE
Component swirl-date-input is not localized

### ISSUE THREAD

**Issue by SGlathe** [getflip/swirl#443]
## Issue summary

The component swirl-date-input is not localized. The component only displays months and days with english translations.

## Expected behavior

The component should respect the users browser-/device-language or have the option to set a language-key.

## Actual behavior

Browser-/Device-language is ignored. Texts are always displayed in english.

![image](https://github.com/getflip/swirl/assets/59645406/5420d574-f766-44f5-82b9-265a48d94530)

## Steps to reproduce the problem

1. Change the browser-/device-language to a language other than english
2. Open a swirl-date-input
3. The calendar displays english translations

## Specifications

- Swirl version number: 0.87.1
- Browser: Firefox 118.0.2 (64-bit)
- Device: Desktop
- Operating System: Ubuntu 22.04.3 LTS

**Comment by Sqrrl** [comment]
Hey. You can pass a "locale" prop to the component. E.g.: `<swirl-date-input locale="de-DE"></swirl-date-input>`
See also: https://swirl-storybook.flip-app.dev/?path=/docs/components-swirldateinput--docs

**Comment by SGlathe** [comment]
Hi @Sqrrl.
Thanks for the clarification, this works perfectly. Next time, I will check with the documentation before opening a new ticket :)
