### ISSUE TITLE
Heading breaks upon line break

### ISSUE THREAD

**Issue by martinneumann** [getflip/swirl#445]
## Issue summary

A swirl-heading does not update anymore through the [text] input in Angular after it had a line break. If the text is short enough not to have a line break, it updates fine.

## Expected behavior

The DOM element should update the rendered text even if it is long enough to cause new lines.

## Actual behavior

The long text is rendered, but no subsequent changes affect the text.

## Steps to reproduce the problem

1. Create a swirl-heading with a [text] input
2. Input some text
3. Change browser width to cause line break or input longer text
4. Try inputting new heading text, it does not update the heading

## Specifications

- Swirl version number: 0.105.1
- Browser: Chrome
- Device: Macbook M1 Pro
- Operating System: macOs Sonoma 14.0

```bash
 System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 75.09 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 115.1.56.20
    Chrome: 117.0.5938.88
    Safari: 17.0
```

**Comment by Sqrrl** [comment]
Fixed with https://github.com/getflip/swirl/pull/451
