### ISSUE TITLE
Date Input: Wrong time selected when the user is in a negative UTC-Timezone

### ISSUE THREAD

**Issue by SGlathe** [getflip/swirl#457]
## Issue summary

When the currents devices timezone is set to one with a negative UTC, e.g. Cape Verde (UTC-1) to Alaska (UTC-9), and a date is selected in the date-picker, the component selects the day before the one that the user selected.

## Expected behavior

The component should select the date that the user clicked on in the date-picker.

## Actual behavior

The components selects the day before the one that the user selected.

## Steps to reproduce the problem

This issue can be reproduced on the example date-input in the documentation:
https://swirl-storybook.flip-app.dev/?path=/story/components-swirldateinput--swirl-date-input

1. Set your devices timezone to negative UTC.
2. Reload the page that displays the date-input.
3. Open the date-picker and select a date.

## Specifications

- Swirl version number: 0.107.0
- Browser: Firefox 119.0 (64-bit)
- Device: Desktop PC
- Operating System: Linux Ubuntu 22.04.3 LTS

**Comment by Sqrrl** [comment]
Should be fixed with v0.111.1. Please re-open if the issue persists.
