### ISSUE TITLE
SwirlDatePicker skips a month when navigating to the next one

### ISSUE THREAD

**Issue by SGlathe** [getflip/swirl#553]
## Issue summary
When selecting a date in the current month, which does not exist in the next month (e.g. January 30, because February 30 is non-existing) and then navigating to the next month, the next month is skiped and the DatePicker shows the month after that.

Update:
The reverse thing happens, when navigating to a previous month whose date does not exist in the currently selected month, e.g. when jumping one month back from march 31 to february. In this case, the datepicker stays in the current month and only clicking the navigation-button again will navigate to february.

## Expected behavior
DatePicker should not skip months on navigation

## Actual behavior
DatePicker skips a month.

## Steps to reproduce the problem
1. Select a date in the current month, that does exist in the next month, e.g. January 30 or 31
2. Navigate to the next month
3. February should be displayed, but instead the Calendar jumps to march.
Issue can be reproduced in the storybook: https://swirl-storybook.flip-app.dev/?path=/docs/components-swirldatepicker--docs

## Specifications
- Swirl version number: 0.116.0
- Browser: 120.0 (64-bit)
- Device: Desktop
- Operating System: Linux Ubuntu 22.04.3 LTS

**Comment by Sqrrl** [comment]
Should be fixed with the latest version.
