### ISSUE TITLE
TimePicker for selecting times

### ISSUE THREAD

**Issue by SGlathe** [getflip/swirl#591]
## Feature request summary

Similar to the SwirlDatePicker, but lets the user select Times (hh:mm - hours and minutes).

## Rationale

This feature was requested by a customer, who wanted an alternative to inputting numbers via the SwirlTimeInput.

**Comment by danizep** [comment]
Hi,

At the moment there's no plan to build a dedicated time picker component.

Nevertheless, a change was made to open the numeric keyboard when inputing time on the SwirlTimeInput.

This change should already greatly improve the UX.

Plese have a look at version [0.159.0](https://github.com/getflip/swirl/releases/tag/%40getflip%2Fswirl-components-angular%400.159.0)
