### ISSUE TITLE
DateInput: Add option to disable manual input and allow only calendar-selection

### ISSUE THREAD

**Issue by SGlathe** [getflip/swirl#592]
## Feature request summary
Add the option to disable the manually date-input and to open the DatePicker immediately instead.

## Rationale
Explain the benefit of this feature
Currently, the DateInput renders an input-field that allows for manually entering a date, but also shows a date selected via the DatePicker. Clicking on the input will open the virtual keyboard on mobile devices. Some customers wished for the behavior, that the DatePicker would open immediately instead and that manual inputting a date is suppressed.

**Comment by joseabernardes** [comment]
Fixed by #607 and #629.
