### ISSUE TITLE
DatePicker: Option to highlight specified days in the calendar

### ISSUE THREAD

**Issue by SGlathe** [getflip/swirl#593]
## Feature request summary
This is a request for a new option for the DatePicker and DateInput, that allows the developer to pass an array of dates to the component, so the rendered calendar can highlight these days.

## Rationale
A customer, who uses this component in an app to track absences, wished for this feature. Context: In the app, users can see an overview of their existing absences / vacations and request new ones. When creating a new absence, the user should see in the DatePicker, which days are already planned for an absence.

**Comment by danizep** [comment]
Hi,

Currently the lib used for the date picker does not support the highlighting of dates.

Nevertheless, a change was made to allow the disabling of arbitrary dates. That said, these disabled dates are styled differently and are not actionable. This should be released soon on version `0.160.0`. 

I hope this helps. 😃 

We will keep in mind the highlighting feature.
